Fix typo in README.md
cloudposse/terraform-aws-vpc-peering-multi-account pull request #34
Opened 2021-01-20 12:12 UTC by Zaargh

fix link to `terraform-aws-vpc-peering` - it was pointing to `terraform-aws-vpc`

2021-01-20 17:05 UTC, mcalhoun commented
@Zaargh it looks like there were no updated files in this PR?

2021-01-20 17:05 UTC, mcalhoun requested changes
Please update the appropriate files

2021-01-21 09:48 UTC, SweetOps reviewed
@Zaargh you should make changes in `README.yaml` not in `README.md` otherwise bot will overwrite your changes

2021-01-21 10:16 UTC, Zaargh commented
> @Zaargh you should make changes in `README.yaml` not in `README.md` otherwise bot will overwrite your changes

Ok, I see :) 

It should be correct now.

2021-01-21 10:21 UTC, SweetOps commented
/test all

2021-01-21 10:30 UTC, SweetOps approved these changes

2021-01-21 10:31 UTC, merged