Revert PR #44
cloudposse/terraform-aws-vpc-peering-multi-account pull request #62
Opened 2022-06-24 17:42 UTC by Benbentwo

## what
* Reverts PR #44 which introduced a bug when using default routing table

## references
* Fixes #45

2022-06-24 17:43 UTC, Benbentwo commented
/test all

2022-06-24 18:53 UTC, aknysh commented on accepter.tf
> +  count                     = module.this.enabled ? local.accepter_aws_route_table_ids_count * local.requester_cidr_block_associations_count : 0
```suggestion
  count                     = local.enabled ? local.accepter_aws_route_table_ids_count * local.requester_cidr_block_associations_count : 0
```

why are you changing from `local.accepter_enabled` to the global enabled?

2022-06-24 18:54 UTC, aknysh commented on accepter.tf
> -  timeouts {
why removing the timeouts?

2022-06-24 18:54 UTC, aknysh reviewed
please see comments

2022-06-24 18:56 UTC, Benbentwo commented on accepter.tf
> -  timeouts {
accidental replacement

2022-06-24 19:14 UTC, Nuru requested changes
The `aws_subnet_ids` resource has been deprecated, and we should use `aws_subnets` instead. 

Although `aws_route_table` has not been deprecated, we should probably use `aws_route_tables` instead, as it has the cleaner, more modern interface.

We can fix the original bug by looking up the default route table and using it if no route table is found to be associated with the subnet.

2022-06-24 19:48 UTC, Benbentwo commented
I believe I addressed your comments.  using `aws_subnet_ids` now. 

We we're already using `aws_route_tables` in the PR so nothing changed there. Tested with one using default route table, and one without.

2022-06-24 19:48 UTC, Benbentwo commented
/test all

2022-06-24 20:17 UTC, Nuru submitted a review, later dismissed
Backtracking on removing `sort` for data from data sources, since it seems to work. See other comments.

2022-06-24 20:17 UTC, Nuru commented on accepter.tf
> +  }
Include [tags](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/subnets#tags)

2022-06-24 20:17 UTC, Nuru commented on accepter.tf
> +  accepter_subnet_ids       = try(local.accepter_enabled ? data.aws_subnets.accepter[0].ids : [], [])
Apparently I was wrong about sorting data with respect to `data` sources, which I guess are now read during the plan phase. (See what goes into the `count` on line 84.) Please revert, as `distinct` and `sort` add stability to the plans.

2022-06-24 20:17 UTC, Nuru commented on accepter.tf
> +  vpc_id   = local.accepter_vpc_id
This is going to add routes to all the route tables in the VPC. I may have said that was a good idea a year ago, but it strikes me as bad/dangerous now. 

I propose that you add a second `aws_route_tables` resource, and use one to filter based on subnet ID and the other to find the default route table. Only add routes to the subnets' route tables, and only add to the main route table if there is a subnet that does not have a route table.

2022-06-24 22:46 UTC, Benbentwo commented
/test all

2022-06-24 23:01 UTC, Benbentwo commented
/test all

2022-06-24 23:05 UTC, Benbentwo commented
/test all

2022-06-28 00:28 UTC, aknysh commented on accepter.tf
> +# If we had more subnets than routetables, we should update the default.
add an empty line between the data sources

2022-06-28 00:30 UTC, aknysh commented on accepter.tf
> +  description = "Accepter VPC subnet to route table map"
```suggestion
  description = "Map of accepter VPC subnet IDs to route table IDs"
```

2022-06-28 00:30 UTC, aknysh commented on accepter.tf
> +output "accepter_route_table_map" {
```suggestion
output "accepter_subnet_route_table_map" {
```

2022-06-28 00:33 UTC, aknysh commented on accepter.tf
> +  accepter_subnet_ids       = try(local.accepter_enabled ? data.aws_subnets.accepter[0].ids : [], [])
do we need `try` here?
it's useful in some cases, but mostly it hides errors that we don't want to hide

2022-06-28 00:34 UTC, aknysh reviewed
@Benbentwo a few nitpicks

2022-06-28 00:41 UTC, Benbentwo commented on accepter.tf
> +  accepter_subnet_ids       = try(local.accepter_enabled ? data.aws_subnets.accepter[0].ids : [], [])
I agree, was thinking of that when writing it. kept in, but there's no need, it's removed now

2022-06-28 02:13 UTC, Nuru commented
/test all

2022-06-28 02:19 UTC, Nuru requested changes

2022-06-28 02:19 UTC, Nuru commented on accepter.tf
> +  }
```suggestion
  tags = var.accepter_subnet_tags
```
See https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/subnets#tags

2022-06-28 02:19 UTC, Nuru commented on accepter.tf
> +}
```suggestion
}

```

2022-06-28 02:27 UTC, Benbentwo commented on accepter.tf
> +  }
totally misread that documentation

2022-06-28 02:30 UTC, Nuru commented
/test all

2022-06-28 02:31 UTC, Nuru approved these changes

2022-06-28 02:35 UTC, aknysh approved these changes

2022-06-28 02:38 UTC, merged