Update accepter.tf
cloudposse/terraform-aws-vpc-peering-multi-account pull request #67
Opened 2022-10-28 10:31 UTC by ngoyal16

## what
* Describe high-level what changed as a result of these commits (i.e. in plain-english, what do these changes mean?)
* Use bullet points to be concise and to the point.

## why
* Provide the justifications for the changes (e.g. business case). 
* Describe why these changes were made (e.g. why do these commits fix the problem?)
* Use bullet points to be concise and to the point.

## references
* Link to any supporting github issues or helpful documentation to add some context (e.g. stackoverflow). 
* Use `closes #123`, if this PR closes a GitHub issue `#123`

2022-10-29 21:10 UTC, Nuru requested changes

2022-10-29 21:10 UTC, Nuru commented on requester.tf
> +  ])
Same as with "accepter": Why is this change necessary? `cidr_block_associations` should have all the IPv4 and IPv6 CIDRs.

2022-10-29 21:10 UTC, Nuru commented on requester.tf
> +  destination_cidr_block      = can(regex("::", local.accepter_cidr_block_associations[count.index % local.accepter_cidr_block_associations_count]["cidr_block"])) ? null : local.accepter_cidr_block_a
I hate using `regex` here,  but could live with it. I definitely do not want to use `can()` here. We don't need a regex, anyway. Use

```hcl
split(":", local.accepter_cidr_block_associations[count.index % local.accepter_cidr_block_associations_count]["cidr_block"]) > 1
```
to determine that the string is an IPv6 CIDR

2022-10-31 05:51 UTC, ngoyal16 commented on accepter.tf
> +  ])
@Nuru  `cidr_block_associations` do not contains IPv6 CIDRs

2022-10-31 05:51 UTC, ngoyal16 commented on requester.tf
> +  ])
@Nuru  `cidr_block_associations` do not contains IPv6 CIDRs

2022-12-08 11:01 UTC, ngoyal16 commented on requester.tf
> +  destination_cidr_block      = can(regex("::", local.accepter_cidr_block_associations[count.index % local.accepter_cidr_block_associations_count]["cidr_block"])) ? null : local.accepter_cidr_block_a
@Nuru  PR has been updated. can you check and let me know if anything extra needs to be added.

2024-03-02 11:29 UTC, closed without merging