fix: access to accepter cidr block
cloudposse/terraform-aws-vpc-peering-multi-account pull request #83
Opened 2024-01-22 11:50 UTC by bmbferreira

## what

This PR changes that by using the filtered subnet cidrs to create the routes instead of using the whole VPC cidr.

## why

Currently even when filtering the accepter subnets by tags, the route table on the requester side is always created to the vpc cidr of the accepter and doesn't create individual routes for each filtered subnet. This is not flexible enough as we might need for example peering to two different VPCs with overlapping CIDRs and we might want to use the subnet cidrs to be able to route to individual cidrs within the subnet, dodging the VPC cidr overlapping.

## references

2024-03-02 11:25 UTC, hans-d commented
/terratest

2024-03-04 01:12 UTC, bmbferreira commented
@hans-d any plans to merge this? the test failure doesn't seem to be related with my change, as I see the same test failin in other PRs as well: https://github.com/cloudposse/actions/actions/runs/8132588929/job/22223186662

2024-03-04 01:17 UTC, hans-d commented
Unfortunately, I cannot bypass this check. Getting some internal visability on these failing tests as well, as they are now popping up in various places (for various different reasons).
Once the blocking bits are gone (soon I hope), this will be revisited.

2024-07-31 11:01 UTC, bmbferreira commented
@joe-niland @dotCipher Hi! What can I do to have this reviewed? Thank you

2024-09-25 23:59 UTC, bmbferreira commented
@goruha just fixed format that was failing. Can you check if the PR is ok to merge? thank you

2024-09-26 15:04 UTC, goruha requested changes
@bmbferreira why do not we have ?

```
data "aws_subnet" "requester" {
```

2024-09-29 01:00 UTC, bmbferreira commented
> @bmbferreira why do not we have ?
> 
> ```
> data "aws_subnet" "requester" {
> ```

Fixed. I applied the same logic to the requester as well. I also did an improvement to fallback to the VPC cidr if no tag filters are passed as inputs. I think it only makes sense to use the filtered subnet cidr blocks if we are actually filtering it. If not we can continue using the vpc cidr. WDYT?

2024-10-02 19:21 UTC, goruha requested changes

2024-10-02 19:21 UTC, goruha commented on accepter.tf
> +  accepter_subnet_ids       = local.accepter_enabled ? data.aws_subnets.accepter[0].ids : []
```suggestion
  accepter_subnet_ids       = local.accepter_enabled ? try(data.aws_subnets.accepter[0].ids, []) : []
```

2024-10-02 19:21 UTC, goruha commented
@bmbferreira I have one request for change.
Beside of that it looks fine

2024-10-02 19:22 UTC, goruha commented
/terratest

2024-10-10 22:52 UTC, goruha commented
/terratest

2024-10-10 23:02 UTC, goruha approved these changes

2024-10-10 23:02 UTC, goruha commented
@bmbferreira Thanks for your contribution

2024-10-10 23:04 UTC, goruha commented
/terratest

2024-10-10 23:18 UTC, merged